### ISSUE TITLE
About the pretrained model

### ISSUE THREAD

**Issue by lzhnb** [autonomousvision/monosdf#16]
Thanks for your amazing work!
Can you share the pretrained model of monosdf?

Good luck!

**Comment by niujinshuchong** [comment]
Hi, pretrained models are uploaded. Please check readme for how to use it.

**Comment by ricklentz** [comment]
@niujinshuchong Thanks again for sharing your novel work!  Can you double-check the S3 permissions for the folder _monosdf_ and the file _pretrained_models.tar_?

**Comment by niujinshuchong** [comment]
@ricklentz Thanks for pointing this out. The link is not working currently because our AWS server does the synchronization only once a day. It should be working in 7 hours. Sorry for the inconvenience.
