### ISSUE TITLE
About  the TNT dataset download link

### ISSUE THREAD

**Issue by lzhnb** [autonomousvision/monosdf#17]
Thanks for your excellent work!
We meet some trouble when downloading the TNT dataset:
![image](https://user-images.githubusercontent.com/49898493/195010902-f4a442bb-69fd-4d54-9782-6ab6770ac754.png)

Would you please update the download link?

Good luck!

**Comment by niujinshuchong** [comment]
Hi, the link is updated. Thanks for reporting this.
