### ISSUE TITLE
some questions about depth_loss

### ISSUE THREAD

**Issue by LiXinghui-666** [autonomousvision/monosdf#18]
Thank you for your excellent work. I would like to know why is this operation performed on **depth_gt** when depth loss is calculated：(**depth_gt * 50 + 0.5**). Corresponding to this line of code:
```python
def get_depth_loss(self, depth_pred, depth_gt, mask):
        # TODO remove hard-coded scaling for depth
        return self.depth_loss(depth_pred.reshape(1, 32, 32), (depth_gt * 50 + 0.5).reshape(1, 32, 32), mask.reshape(1, 32, 32))
```

**Comment by niujinshuchong** [comment]
Hi, the monocular depth output is small and it's in the range of 0.01 to 0.04, and the loss will be very small so we simply scale them to some large value.

**Comment by LiXinghui-666** [comment]
Thank you for your reply!

**Comment by LiXinghui-666** [comment]
culart

> Hi, the monocular depth output is small and it's in the range of 0.01 to 0.04, and the loss will be very small so we simply scale them to some large value.

There's the same question about scale scaling. Since a scale and shift are calculated in advance when the depth loss is calculated, what is the function of the following line in the code?
```python
# we should use unnormalized ray direction for depth
ray_dirs_tmp, _ = rend_util.get_camera_params(uv, torch.eye(4).to(pose.device)[None], intrinsics)
depth_scale = ray_dirs_tmp[0, :, 2:]
depth_values = depth_scale * depth_values
```
