### ISSUE TITLE
evaluation result on tanks and temples dataset

### ISSUE THREAD

**Issue by CanCanZeng** [autonomousvision/monosdf#2]
Hi, thank you for sharing this great work, the mesh created by monosdf looks very impressive! Have you evaluated the result on tanks and temples dataset? I'd like to know the metric accuracy of monosdf.

**Comment by niujinshuchong** [comment]
Yes, you can find the results in table 8 in the supplementary.

**Comment by CanCanZeng** [comment]
Thank you for your kind reply @niujinshuchong ! But I'm not very sure of the meaning of numbers in table 8. Does it mean the 
 percentage of points (from mesh) that has an error under 10mm? How can I compare the result with other MVS methods?

![image](https://user-images.githubusercontent.com/26817559/178623670-75f4a49a-4729-4dcb-9e43-bf68790bbf78.png)
![image](https://user-images.githubusercontent.com/26817559/178623738-1123ead9-a381-4b78-9f89-ee6d15da738e.png)

**Comment by niujinshuchong** [comment]
Hi, the F-score a combination of accuracy and completeness (precision and recall). Please refer to https://en.wikipedia.org/wiki/F-score

The result in Table 8 is the same metric as your screenshot so you can directly compare to MVS methods if you want.

**Comment by CanCanZeng** [comment]
Okay, I know. But this result is too unexpected for me. Why does the mesh look so good, but the metric quality is so poor? Is it ascribe to the too sparsity of mesh vertex? Can you post the precision and recall score of the result from monoSDF?

**Comment by niujinshuchong** [comment]
I think there are several reasons. 

1. We extract the mesh with a 768^3 cube which is small in the T&T scenes. The mesh is about 40MB in the disk while Vis-MVSNet's point cloud is ~1GB. I am not sure how this affect the quantitative results. 
2. The threshold for F-score is too small. 10mm in T&T while we find the average error is about 3cm in ScanNet. We use 5 cm as threshold in ScanNet (as other paper). 
3. We didn't filter the mesh as in ScanNet. So there are some faces not visible in any camera but it's still present in the mesh. This will make the quantitative results worse.

I don't have the precision and recall as the evaluation server only return the F-score.

**Comment by CanCanZeng** [comment]
Thank you for your detailed explanation! When will you open source the code? Or can you upload the extracted mesh so that I can help find why the metric score is so weird. (I cannot download the mesh you uploaded to Sketchfab)

**Comment by niujinshuchong** [comment]
We will release the code later. I am not sure what is the exact timeline but hopefully soon. 

You can download the reconstructed mesh here https://drive.google.com/file/d/1Cr-UVTaAgDk52qhVd880Dd8uF74CzpcB/view?usp=sharing

**Comment by CanCanZeng** [comment]
Hi, I quickly went through the mesh produced by monosdf and compared it to the pointcloud produced by ACMP. I guess the mesh is too smooth so the evaluation result is so bad. And I suspect that the monocluar depth will introduce some negative effect, since as far as I know, depth estimated by monocluar depth algorithm offen has big difference for patches with difference texture(color) even if they are on the same plane. 

below are some screen shots of comparison between monosdf and ACMP
![Screenshot from 2022-07-18 15-00-45](https://user-images.githubusercontent.com/26817559/179460272-0697b399-3866-419b-a2e2-d933214e72ba.png)
![Screenshot from 2022-07-18 15-03-21](https://user-images.githubusercontent.com/26817559/179460295-1faa1cf8-50de-4847-b9e6-7f18ee7937bb.png)
The colored points are from ACMP and the yellow points are vertices of mesh from monosdf. I guess the roof is more like a sphere as ACMP reconstructed.  And These surrounding point clouds should be more straight because they are all walls

**Comment by CanCanZeng** [comment]
By the way, although the result is not ideal, it is amazing enough in my opinion.

**Comment by niujinshuchong** [comment]
@CanCanZeng Thanks for your insightful comments.
