### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE

### ISSUE THREAD

**Issue by morsingher** [autonomousvision/monosdf#20]
Hi, I was trying to run some pretrained model, but I keep getting the following error:
![Screenshot from 2022-10-11 11-52-14](https://user-images.githubusercontent.com/36917382/195058638-3ecdf26b-9d85-4301-9ec3-39ec60653f53.png)
I followed all the steps in the readme to create the environment and install the correct libraries. Any ideas on why this happens? Thank you in advance for the help.

**Comment by morsingher** [comment]
Moreover, I know this is unrelated to the current issue, but note that the new script for downloading meshes returns an "access denied" error.

**Comment by morsingher** [comment]
For some reasons I can't understand, the issue is with PyTorch 1.12. Downgrading to 1.10 solved the issue.

**Comment by niujinshuchong** [comment]
Great that you solved the problem. The link for downloading the meshes should be working tomorrow.

**Comment by botaoye** [comment]
Hi, I have the same probelm even using Pytorch 1.10.
