### ISSUE TITLE
About the training time

### ISSUE THREAD

**Issue by botaoye** [autonomousvision/monosdf#23]
Hi, thanks for your excellent work. When re-producing the scanner scene 1 results, I found that it takes more than 1 day to train an MLP model on a single NVIDIA RTX3090 GPU, which is much longer than the reported time in your paper. Is this normal? Since I found that you always train 1000 epochs for each time, thus causing different training time for each scene.

**Comment by niujinshuchong** [comment]
Hi, the time is measured in a replica scene without saving visualization results. You are correct. Different scenes might have different training time.

**Comment by botaoye** [comment]
Okay, thanks for your reply.
