### ISSUE TITLE
The depth and normal about TnT

### ISSUE THREAD

**Issue by lzhnb** [autonomousvision/monosdf#25]
Thanks for your amazing work!

I have a few questions about the depths and normals for the TnT dataset.

The origin size of images in TnT is **[1080, 1920]**, and the size of your provided images and estimated depth&normal maps is **[1152, 2048]**, why do you scale the image?

Otherwise, I run the script `preprocess/extract_monocular_cues.py` to estimate depth&normal map, but it only works on the **[384, 384]** images due to the limitation of the omnidata.

So, how can you obtain the depth&normal maps for the TnT dataset?

Good luck!

**Comment by lzhnb** [comment]
Ok, I found this in your supplementary:
![image](https://user-images.githubusercontent.com/49898493/195842641-820ef33c-5836-4985-b524-428077e79ad4.png)

**Comment by niujinshuchong** [comment]
@lzhnb We do have a subsection for this in the paper but not the part you highlighted. Please check C.3 in our updated arxiv paper.

**Comment by lzhnb** [comment]
> @lzhnb We do have a subsection for this in the paper but the part you highlighted. Please check C.3 in our updated arxiv paper.

Thanks for your quick reply!
