### ISSUE TITLE
Missing data and config files for DTU

### ISSUE THREAD

**Issue by woominsong** [autonomousvision/monosdf#26]
Hi, thanks for sharing such wonderful work!

It seems that some data and config files for DTU are missing, including:
 - config files for MLP experiments (only MLPGrid version is provided)
 - DTU_padded_highres dataset, referenced in dtu_mlp_fullres_allviews.conf

Could you share those files, too?
Thanks in advance!

**Comment by niujinshuchong** [comment]
Hi, 

1. here are the config files for MLP experiments in the DTU dataset: https://github.com/autonomousvision/monosdf/blob/main/code/confs/dtu_mlp_3views.conf and https://github.com/autonomousvision/monosdf/blob/main/code/confs/dtu_mlp_fullres_allviews.conf
3. you can run this script to generate DTU_padded_highres: https://github.com/autonomousvision/monosdf/blob/main/preprocess/paded_dtu.py

**Comment by woominsong** [comment]
Thanks for the quick reply!

I'm a little confused about the config files, because [Grid_MLP was set to True](https://github.com/autonomousvision/monosdf/blob/main/code/confs/dtu_mlp_3views.conf#L38).
Are those config files for single-res feature grid experiments, or are they for MLP?
(I thought MLP did not use any feature grid)

Thanks!

**Comment by niujinshuchong** [comment]
Hi, the difference is here: https://github.com/autonomousvision/monosdf/blob/main/code/confs/dtu_mlp_3views.conf#L50

We concat an all zeros feature when use MLP only.

**Comment by woominsong** [comment]
Thanks a lot for your kind reply!
