### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by Thermaloo** [autonomousvision/monosdf#28]
Thanks for your work. I'm a green hand. I do not understand the get_sphere_intersections function in code/utils/rend_util.py. Could you please give me some hints? How does it compute the intersection？

**Comment by niujinshuchong** [comment]
Hi, maybe you can check it here: https://en.wikipedia.org/wiki/Line–sphere_intersection

**Comment by Thermaloo** [comment]
Thank you very much!
