### ISSUE TITLE
How does monosdf get the pose of tanks and temples dataset ?

### ISSUE THREAD

**Issue by rainfall1998** [autonomousvision/monosdf#3]
Thank you for this great work, the result of tanks and temples dataset looks impressive! 

Recently I tested volsdf  on this dataset , using the pose provided by colmap, but basically could not reconstruct a reasonable shape. I notice that the test datasets are also tested. How does monosdf get pose of this dataset?

Thanks for your help and looking forward to your reply

**Comment by niujinshuchong** [comment]
Hi, we used the preprocessed data from Vis-MVSNet which I think is originally provided by MVSNet. You can download it in Data preparation in https://github.com/jzhangbs/Vis-MVSNet

**Comment by rainfall1998** [comment]
Thanks!
