### ISSUE TITLE
Question about paper

### ISSUE THREAD

**Issue by DongyangHuLi** [autonomousvision/monosdf#30]
Hi, I have some doubts about formula 8 in the paper. I can't find a similar calculation method in reference [75]. Could you please give me some tips? Thank you.

**Comment by niujinshuchong** [comment]
Hi, maybe you are reading two different versions of our paper. Please refer to https://arxiv.org/pdf/2106.12052.pdf Eq. 3. also check our updated paper in arxiv.

**Comment by DongyangHuLi** [comment]
OK，Thank you so much！
