### ISSUE TITLE
Higher Resolution inputs from Omnidata

### ISSUE THREAD

**Issue by pablovela5620** [autonomousvision/monosdf#31]
Appreciate you all open-sourcing the code! I was wondering about your presentation [here](https://youtu.be/zCE0lOCWPqg?t=1176), it's mentioned using higher resolution cues (depth/normals). Are there any plans on releasing the code that does the sliding window + merging to generate these higher resolution cues?

Thanks again

**Comment by hbell99** [comment]
I am also wondering whether the code using higher resolution cues (depth/normals) will be released.

Thanks for your time!

**Comment by niujinshuchong** [comment]
Hi, the script for generating high-resolution cues is uploaded. Please check README for how to run it.

**Comment by pablovela5620** [comment]
Awesome,. Thanks for the quick response
