### ISSUE TITLE
Question about the normal computed in Eq(10) in the paper.

### ISSUE THREAD

**Issue by hbell99** [autonomousvision/monosdf#32]
Hi,

Before all, thank you for your inspiring work! 

I would like to ask some questions about the \hat{N}(r) computed in equation (10).
![image](https://user-images.githubusercontent.com/72784281/198181761-d55a5480-01b0-49c0-b045-4f06c7b0d68d.png)

If I understand it correctly, the direction of the normal vector calculated at the sampling points \hat{n}_r^i on each ray might be different. Then why does the volume rendering formula used to calculate \hat{N}(r) can **represent the surface intersecting the current ray**？

Thank you for your time!

**Comment by niujinshuchong** [comment]
Hi, 

It's an approximation. It's true that points on the ray will have different normals. But during training, the model will converge so the sampled points will be very close to the real surface.

**Comment by hbell99** [comment]
Many thanks to your reply!

I can see what it means now.

**Comment by hbell99** [comment]
> Hi,
> 
> It's an approximation. It's true that points on the ray will have different normals. But during training, the model will converge so the sampled points will be very close to the real surface.

Many thanks to your reply!

I can see what it means now.
