### ISSUE TITLE
RuntimeError: shape '[1, 147456, 3]' is invalid for input of size 5760000

### ISSUE THREAD

**Issue by jaymefosa** [autonomousvision/monosdf#33]
Trying to train scan24 with the multi-res grid all-views. Training seems to get through the first epoch

```
Traceback (most recent call last):
  File "training/exp_runner.py", line 71, in <module>
    trainrunner.run()
  File "monosdf/code/../code/training/monosdf_train.py", line 225, in run
    plot_data = self.get_plot_data(model_input, model_outputs, model_input['pose'], ground_truth['rgb'], ground_truth['normal'], ground_truth['depth'])
  File "monosdf/code/../code/training/monosdf_train.py", line 295, in get_plot_data
    rgb_eval = model_outputs['rgb_values'].reshape(batch_size, num_samples, 3)
RuntimeError: shape '[1, 147456, 3]' is invalid for input of size 5760000
```

**Comment by niujinshuchong** [comment]
Hi, are you training with full-res all views on the DTU? Did you use the script https://github.com/autonomousvision/monosdf/blob/main/preprocess/paded_dtu.py to generate the training data? Or maybe you could set the image resolution here https://github.com/autonomousvision/monosdf/blob/main/code/confs/dtu_grids_fullres_allviews.conf#L29

**Comment by jaymefosa** [comment]
@niujinshuchong Hi thanks it works after running the padding script. I thought the data was already preprocessed. Thanks again!
