### ISSUE TITLE
Single-res grids model and config files

### ISSUE THREAD

**Issue by alvin528** [autonomousvision/monosdf#35]
Thank you so much for sharing such interesting work! 
I found some experiments on Single-res grids in the paper, and I would like to reproduce these results. Can you share the model and configuration files?

**Comment by niujinshuchong** [comment]
Hi, we use the following config 
```
base_size = 128
end_size = 128
logmap = 24
num_levels= 4
level_dim= 8
```
to https://github.com/autonomousvision/monosdf/blob/main/code/confs/replica_grids.conf#L51 for single-res grids.

**Comment by alvin528** [comment]
Thank you for your reply!
