### ISSUE TITLE
About the figure 19 in your final version paper

### ISSUE THREAD

**Issue by zhao-yiqun** [autonomousvision/monosdf#36]
Hi,

Thanks for your code sharing, I wonder what the different columns of Figure 19 means. Are there both with depth and normal cues? The caption of Fig.19 did not mention about that

Since I try to reproduce the single-res grids with all views without any cues and found the surface is noisy like followings. Therefore I wonder whether your single-res without any cues may cause this.

Regards

![image](https://user-images.githubusercontent.com/91787021/198916761-ae788236-057f-496d-91db-b9565a0dde0f.png)

**Comment by niujinshuchong** [comment]
Hi, 

thanks for pointing this out! The order is the same as the figure in Table 5. You result looks reasonable to me. Do you use our code base?

**Comment by zhao-yiqun** [comment]
Thans for your quickly reply. 

Is it resonable for single-res Voxel-based dtu without any cues? 

I did not use the code from your code base, but I just changed from volsdf to NeuS and used the mask.  without mask for single-res NeuS may be even worse. I found you have implement some similar experiments, therefore just consulting you to check whether it is a difference caused by volsdf and NeuS or the single-res voxel.

Regards

**Comment by niujinshuchong** [comment]
Hi, 

I got similar results at the beginning of this project. You could try to increase the resolution of the feature grids, or use smooth trilinear interpolation https://github.com/autonomousvision/monosdf/blob/main/code/hashencoder/src/hashencoder.cu#L87  (also see appendix in instant-ngp) or simply use our provided multi-res. girds .

**Comment by zhao-yiqun** [comment]
Thanks for your quick reply. I will have a try.

Best regards.
