### ISSUE TITLE
Results of MLP and grids  

### ISSUE THREAD

**Issue by jzhzhang** [autonomousvision/monosdf#37]
Thanks for sharing the code. We have tested the released pre-trained weights of both ```mlp``` and ```grids``` on scan 1. 

But we found that the ```grids```, which uses the instant-ngp, is worse than the simple ```mlp```:
```scannet_grids.conf```:
![image](https://user-images.githubusercontent.com/54199992/199062025-aeca037c-2f22-45e0-a120-ac83d2676a08.png)
```scannet_mlp.conf```:
![image](https://user-images.githubusercontent.com/54199992/199062204-94cb27fe-b2e0-4aac-a48c-977b9af9927e.png)

I am not sure it's not an expected result of the paper. Can you give me some ideas about the results? Thanks in advance.

**Comment by zhao-yiqun** [comment]
You can refer to the section 4.1 and Table 2 of the paper for the experiment results between mlp and ngp, which illustrated that with both cues, ngp is worse than mlp.

**Comment by jzhzhang** [comment]
Thanks. Really appreciate your quick response.
