### ISSUE TITLE
Has the training script been tried on Windows?

### ISSUE THREAD

**Issue by Pipe-Runner** [autonomousvision/monosdf#38]
There are a lot of blockers with the distributed training when it comes to a windows machine. 
- backend needs to be set to `gloo`
- Ninja needs to be installed separately
- `local_rank` are missing in the sample training command.
As of now, I have not managed to progress further with the training, as there seems to be another error 

Please excuse my ignorance if I have missed something obvious. Your guidance will be invaluable to me. Thank you.

Edit: It might be a problem with my torch installation, so I'll repeat the steps on Linux as well. Sorry for the inconvenience.

**Comment by niujinshuchong** [comment]
Hi, we didn't test it with Windows. I don't know how I can help.
