### ISSUE TITLE
Question about ScanNet evaluation code

### ISSUE THREAD

**Issue by alvin528** [autonomousvision/monosdf#39]
Hi, I would like to ask why the ScanNet evaluation code uses GTmesh_lowres instead of GTmesh?
[https://github.com/autonomousvision/monosdf/blob/f4393ef3a2639a580890c88bc1e6959cfca84803/scannet_eval/evaluate.py#L183](url)
And how is GTmesh_lowres generated?

**Comment by niujinshuchong** [comment]
Hi, we follow Manhattan SDF to do the evaluation, and GTmesh_lowres is provided by Manhattan SDF. I think it's the TSDF fusion result but extracts the mesh at low resolution.
