### ISSUE TITLE
The estimated depth results of ScanNet via omnidata model

### ISSUE THREAD

**Issue by lzhnb** [autonomousvision/monosdf#4]
Thanks for your amazing work!

As you said in the paper, you leverage the omnidata model to estimated both monocular depth and normal. We've downloaded the pretrained provided by the official, and it really performs well in the details.
However, we found that the range of the estimated depth is so small. Here is the result of one image from **0616** scene in ScanNet.
![c12c2e276c3e072c1198b4d33fce781](https://user-images.githubusercontent.com/49898493/182100912-f0a5150a-6896-4bee-8338-1f33cd6c27fc.jpg)

In our acknowledge, the range of depth in ScanNet should be `0~3`. How do you process such estimated depth?

Good luck :)

**Comment by niujinshuchong** [comment]
Hi, we use scale-invariant loss to use omnidata depth so the range of output dosen't matter.

**Comment by jzhzhang** [comment]
@niujinshuchong  
I also notice that your code recommends using ominidata to obtain the depth and normal for custom datasets. I wonder if there will be a performance drop when we instead use real depth maps from depth sensors.

**Comment by niujinshuchong** [comment]
@jzhzhang If you have real depth map then you don't need to use scale-invariant loss. You could use MSE or L1 loss directly.
