### ISSUE TITLE
Could monosdf work with CUDA11.6?

### ISSUE THREAD

**Issue by raynehe** [autonomousvision/monosdf#41]
Hello! Thanks for the amazing work!

I'm wondering could this project work with `cudatoolkit==11.6` and `cudatoolkit-dev==11.6` instead of 11.3?

**Comment by niujinshuchong** [comment]
Hi, I think it should work if you install pytorch version properly.

**Comment by raynehe** [comment]
Sorry for being unclear. My question is that, it seems that CUDAToolkit-dev only has 11.4 version (https://anaconda.org/conda-forge/cudatoolkit-dev).

If I install `cudatoolkit=11.6` and `cudatoolkit-dev=11.4`, would that cause any inconsistency?

Thanks!

**Comment by raynehe** [comment]
Sorry to bother again, I'm wondering whether it is doable to install different version of cudatoolkit & cudatoolkit-dev, for we're hoping to use cuda11.6 in our work.
Could you give me a hint about that?
Many thanks!  :-)

**Comment by niujinshuchong** [comment]
@raynehe I am not sure. I think you can simply try it out and you will know.

**Comment by YJ-142150** [comment]
Did you solved the problem? I'm using CUDA 11.7, but have some errors.

**Comment by raynehe** [comment]
@YJ-142150 I'm sorry, I couldn't run this with CUDA11.6, there's some version conflicts with CUDA that I can't fix.
