### ISSUE TITLE
Speeding up training time

### ISSUE THREAD

**Issue by morsingher** [autonomousvision/monosdf#43]
Hi, thanks for open sourcing this amazing work. 

I was wondering why it takes so long to train with multi-resolution grids from Instant-NGP. Intuitively, I would expect it to be sort of "instant". One of the authors of Instant-NGP recently gave a talk at ECCV (https://vimeo.com/764661490) claiming that the speed-up is given by 1) the hash encoder, 2) fully-fused neural networks (i.e. from https://github.com/NVlabs/tiny-cuda-nn) and 3) efficient rendering. You clearly have 1), but maybe missing 2) and 3). 

Is this the case, or am I missing something else? Do you think it's possible to achieve "instant" training of MonoSDF somehow? Thank you in advance for your answer!

**Comment by niujinshuchong** [comment]
Hi, I think it's possible to speed up the training with technique from instant-ngp. 

1) Yes. 2) it's not supported because we need double backward of the MLP. 3) what do you mean by efficient rendering?

**Comment by morsingher** [comment]
What do you mean by "double backward"? Is it for computing the Eikonal loss? 

For efficient rendering, the talk was not particularly clear, he just mentioned skipping empty parts and something like that. I might have to look into their code to get a better grasp.

Thank you anyway, I just wanted to know if you think this is possible :)

**Comment by niujinshuchong** [comment]
Yes, we need to compute the eikonal loss which needs double backward.

**Comment by pablovela5620** [comment]
For efficient rendering, one could use something like https://github.com/KAIR-BAIR/nerfacc which has implemented effieicnet ray marching and volume rendering. Could give a significant speed up. An example that uses this technique in the realm of surface volume rendering is https://github.com/bennyguo/instant-nsr-pl. I'm currently working on porting over monosdf/neuris to this to speed things up hopefully!
