### ISSUE TITLE
High resolution real scene training

### ISSUE THREAD

**Issue by BingHanOfUESTC** [autonomousvision/monosdf#44]
Hello, I had a problem trying to train high resolution NeRF using real-life images to get a better mesh. Beta always changed to none after a few steps. My  high resolution data processing is the same as the one you provided. And my parameters is the same as "tnt_highres_grids_courtroom.conf". Could you please give me some advice?

**Comment by niujinshuchong** [comment]
Hi,

How do you set the camera poses? Is your camera poses normalised? And could you share an image of your dataset?

**Comment by BingHanOfUESTC** [comment]
@niujinshuchong Thank you for your reply. 
I seem to found the cause of my problem. Depth related loss is strongly affected by depth scale and shift factor. And high resolution depth images generated by "generate_high_res_map.py" probably not suitable for my dataset.

**Comment by niujinshuchong** [comment]
@BingHanOfUESTC The monocular depth is scaled hard-coded here https://github.com/autonomousvision/monosdf/blob/main/code/model/loss.py#L190

You could try to tune the weight for depth loss.

**Comment by BingHanOfUESTC** [comment]
@niujinshuchong Thanks a lot!
