### ISSUE TITLE
About scene boundary

### ISSUE THREAD

**Issue by lazyDamon** [autonomousvision/monosdf#46]
Hi, 
The depth and normal information of the floor scene was lost，when I train high resolution real scene images. Could you please give me some advice?
![normal_710_18](https://user-images.githubusercontent.com/80307839/203890375-6b16c401-cdc1-46ac-812a-5dd31fd0fcfa.png)

**Comment by niujinshuchong** [comment]
@lazyDamon We also observe using multi-res. grids give noise results when we  do experiments on scannet dataset. I think you could try to increase the weights for smoothness loss or try something like using large smoothness loss at the beginning of training and slowly decrease the weight for smoothness.

**Comment by lazyDamon** [comment]
@niujinshuchong We can see the scene that in the green box area is lost. It leads to difference between mesh and the real scene. I wonder if this is caused by the smooth? Or is it caused by the set boundary? In your project, you should normalize the scene into a cube. I want to know how you did it, and what is its scale?
![2](https://user-images.githubusercontent.com/80307839/204963459-9054945a-63dd-49de-bf17-27280040b63b.png)

**Comment by niujinshuchong** [comment]
Hi, the normalization is here https://github.com/autonomousvision/monosdf/blob/main/preprocess/scannet_to_monosdf.py#L75-L83

**Comment by lazyDamon** [comment]
OK, thanks for your great work!

**Comment by Yzhbuaa** [comment]
@lazyDamon Hello Damon, have you solved this problem? I observed the same thin structure loss on my own datasets. Could you share how to solve this problem? Thank you!
