### ISSUE TITLE
question about  how to make the video clip 

### ISSUE THREAD

**Issue by fangchuan** [autonomousvision/monosdf#47]
Hi, thanks for open sourcing this amazing work. I have test the code and the result is fine.
I have a non-algorithmic question for you. You showed the awesome mesh reconstruction results on the project page. I would like to know what tools you used to render that video. The input was mesh and the output was a video clip. @niujinshuchong

**Comment by niujinshuchong** [comment]
Hi, we used open3d for rendering.

**Comment by fangchuan** [comment]
> Hi, we used open3d for rendering.

Great, I also use open3d to render images from the resulting mesh, but I fail to copy with the appropriate illumination and shadow, so the output video is not good enough, Could you share your rendering code snippet? I want to check if there is anything I get wrong with the open3d.visualization settings.

**Comment by niujinshuchong** [comment]
Hi, the script for rendering is uploaded here: https://github.com/autonomousvision/monosdf/blob/main/render/render_tntvideos_open3d.py

**Comment by fangchuan** [comment]
> Hi, the script for rendering is uploaded here: https://github.com/autonomousvision/monosdf/blob/main/render/render_tntvideos_open3d.py

Thanks, I really appreciate your help!
