### ISSUE TITLE
Problem about the Grid model and MLP model.

### ISSUE THREAD

**Issue by CZ-Wu** [autonomousvision/monosdf#48]
Hi, thanks for your excellent work!
I am trying to read your code. I find the MLP model defined by the config file is a little different from the one described in your paper. On your code side, you set `Grid_MLP = True` for MLP model, which means you use feature grids and it's not a pure MLP model, right?

**Comment by niujinshuchong** [comment]
Hi, we use the flag use_grid_feature for this. Please check here: https://github.com/autonomousvision/monosdf/blob/main/code/model/network.py#L245-L249
