### ISSUE TITLE
error: no instance of overloaded function "atomicAdd" matches the argument list

### ISSUE THREAD

**Issue by yxt7979** [autonomousvision/monosdf#49]
Hi, thank you for your wonderful work! I have a same error with #19 , 
to solve it I comment all places using atomicAdd in hashencoder.cu. 
Will it have any effects?Thanks~

**Comment by niujinshuchong** [comment]
Hi, I think it don't have any effects because we don't use half precision (float16) during training.

**Comment by yxt7979** [comment]
Thanks~
