### ISSUE TITLE
Eikonal loss with Multi-Resolution Feature Grids

### ISSUE THREAD

**Issue by lambdald** [autonomousvision/monosdf#5]
Thanks for your great work!
As far as I know, eikonal loss requires the use of automatic differentiation to calculate higher order derivatives， like volsdf or neus. In this way, the second-order gradient can be used to optimize the eikonal loss, which is the first-order gradient. But how to implement the second order gradient of the feature grid?

**Comment by niujinshuchong** [comment]
Hi, we implemented second order gradients of the feature grid based on the torch-ngp repo https://github.com/ashawkey/torch-ngp. Now I also found tiny-cuda-nn has official support for it, https://github.com/NVlabs/tiny-cuda-nn. Or you can also use a custom grid_sample function with pytorch https://gist.github.com/niujinshuchong/d88393f346421d358d3a91c4b7751c64 but need to adapted to multi-res feature grids.

**Comment by lambdald** [comment]
thanks for your reply!
