### ISSUE TITLE
Does MonoSDF handle non-NDC coordinate?

### ISSUE THREAD

**Issue by mwang625** [autonomousvision/monosdf#52]
Hi,

Thanks for the great work and your answers before. 

I am wondering if I can train MonoSDF on the blender dataset from the original NeRF paper? In `nice_slam_apartment_to_monosdf.py` the scene is normalized into a unit cube, which means NDC coordinate if I'm not mistaken. Does it work for blender dataset, with views from the upper sphere? As mentioned in Mip NeRF:

> "NDC coordinates can only be used for these "forward-facing" scenes; in scenes where the camera rotates significantly (which is the case for the vast majority of 3D datasets) NeRF uses conventional 3D "world coordinates""

I created the cameras.npz file as suggested for the blender dataset, and transform the pose to the coordinate system in MonoSDF, but still have issues to get the correct results because of the scale_mat. Would you suggest different ways to process the Blender dataset, to make it work on MonoSDF?

Thanks in advance!

**Comment by niujinshuchong** [comment]
Hi， MonoSDF works in Euclidean space so yes, it handle non-NDC space. I think for the blender scene, the coordinate system is x -> right, y -> up and z -> backward while we use x ->right and y -> down and z -> forward. What you need to do is something like poses[:, :3, 1:3] *= -1.

**Comment by mwang625** [comment]
Thanks for your quick reply! I did what you suggested but still got troubles with poses. Is it possible to just load the transformation (c2w) matrix from the raw json from the Blender dataset, without scaling and decomposing the projection matrix in scene_dataset.py? In this case,  `scene_bounding_sphere` was set as 5, but is there anything else I need to change if no scaling is applied?

**Comment by mwang625** [comment]
thanks for your suggestion!
