### ISSUE TITLE
Question about ScanNet evaluation code

### ISSUE THREAD

**Issue by wangm-buaa** [autonomousvision/monosdf#54]
Hi, I found a problem when I ran the ['scannet_eval/evaluate.py'.](https://github.com/autonomousvision/monosdf/blob/main/scannet_eval/evaluate.py)
Specifically，I could successfully load the mesh generated by ['code/evaluation/eval.py'](https://github.com/autonomousvision/monosdf/blob/main/code/evaluation/eval.py).
![image](https://user-images.githubusercontent.com/32636409/209261785-77617d10-4303-4030-a088-13d0112138d7.png)

However，the mesh changed to 'None' after [‘mesh = refuse(mesh, pose, K)’](https://github.com/autonomousvision/monosdf/blob/d9619e948bf3d85c6adec1a643f679e2e8e84d4b/scannet_eval/evaluate.py#L175) finished

![image](https://user-images.githubusercontent.com/32636409/209262658-21dbd641-d3f0-4cf6-941a-6a4c00125ff0.png)
![image](https://user-images.githubusercontent.com/32636409/209262718-e4335e9d-77a4-4f78-9eac-51c71d270a2e.png)

How can I solve this problem?

**Comment by niujinshuchong** [comment]
@wangm-buaa Hi, do you use --world_space when you run eval.py?

**Comment by wangm-buaa** [comment]
> @wangm-buaa Hi, do you use --world_space when you run eval.py?

Yes, and the parameters I used are as follows
` python evaluation/eval.py --conf confs/scannet_mlp.conf --checkpoint <my .pth file path> --world_space --scan_id 1`.

I tried to evaluate the result mesh of scene0050_00(scan1) and unfortunately this problem still exists.

The result mesh seems well.
![image](https://user-images.githubusercontent.com/32636409/209312502-820cdde5-e5d7-45c3-ba66-4a7408abc080.png)

**Comment by niujinshuchong** [comment]
Hi, you don't need to use `--world_space` because we will transform the extracted mesh to world space in the evaluation script here
https://github.com/autonomousvision/monosdf/blob/main/scannet_eval/evaluate.py#L164-L167

Or you can disable the transformation in the evaluation script.

**Comment by wangm-buaa** [comment]
> Hi, you don't need to use `--world_space` because we will transform the extracted mesh to world space in the evaluation script here https://github.com/autonomousvision/monosdf/blob/main/scannet_eval/evaluate.py#L164-L167
> 
> Or you can disable the transformation in the evaluation script.

That works! I sincerely thank you for your patient guidance.
