### ISSUE TITLE
pyhocon new version is not compatible with your implementation

### ISSUE THREAD

**Issue by miangoleh** [autonomousvision/monosdf#57]
Hey. I noticed that "pyhocon" has released a 3.60 version that is not compatible with your code (https://pypi.org/project/pyhocon/#history). 

I wanted to suggest that you specify the previous version in your requirement file to avoid future issues. I tried the following and it worked. 

`pip install pyhocon==0.3.59`

**Comment by niujinshuchong** [comment]
Hi, thanks for the suggestion. It's updated.
