### ISSUE TITLE
Preprocess script for the official DTU dataset

### ISSUE THREAD

**Issue by mwang625** [autonomousvision/monosdf#58]
Hi authors, thanks for the inspiring and awesome work!

One question about the DTU dataset, where can I find the code to process the raw official DTU dataset( https://roboimagedata.compute.dtu.dk/?page_id=36) to the one you provided (https://s3.eu-central-1.amazonaws.com/avg-projects/monosdf/data/DTU.tar)? I'm curious about which set of images (cleaned or rectified) and what exposure did you use. Sorry if I missed the code somewhere in the repo, thanks in advance for your help!

**Comment by niujinshuchong** [comment]
Hi, the DTU is preprocessed by volsdf. You could refer to their repo for more details.
