### ISSUE TITLE
Replica dataset camera path

### ISSUE THREAD

**Issue by Burningdust21** [autonomousvision/monosdf#6]
Hi, thanks for a great work!
The Replica dataset is used in experiments, so I was wondering would you publish the camera path for each scene?

**Comment by niujinshuchong** [comment]
Hi, you can download the dataset from the nice-slam repo. https://github.com/cvg/nice-slam/blob/master/scripts/download_replica.sh

**Comment by Burningdust21** [comment]
Thanks for your reply!
