### ISSUE TITLE
DTU Mesh for Evaluation table

### ISSUE THREAD

**Issue by mwang625** [autonomousvision/monosdf#60]
Hi authors,

Thanks for your amazing work and quick replies to issues. I have a question about the Table 5 in the paper, about chamfer distance evaluation for DTU: 
<img width="848" alt="Screen Shot 2022-11-22 at 11 15 45 AM" src="https://user-images.githubusercontent.com/55957131/224734976-f792eaf9-c633-48e6-9d0d-59f041073100.png">

I'm wondering are the reconstructed meshes from MonoSDF in this table the same as those in the download script (https://s3.eu-central-1.amazonaws.com/avg-projects/monosdf/meshes.tar)? Because I used the meshes from `dtu_allviews_mlp` folder and ran `eval.py` under dtu_eval folder, but chamfer scores (last column in DTU.csv file, shown in the image below) cannot match with the 2nd last row in the table above. 
<img width="865" alt="Screen Shot 2023-03-13 at 3 49 41 PM" src="https://user-images.githubusercontent.com/55957131/224737828-148c81e0-ada9-4a4b-a2cc-6e04675fbf9a.png">

Does it has something to do with the culling step? Below is the culled mesh for scan 65, it seems like some background mesh is not cleaned.
![Screen Shot 2023-03-13 at 3 55 22 PM](https://user-images.githubusercontent.com/55957131/224739398-47a5bee0-3eca-4ca1-849a-867d406089fa.png)

I'd really appreciate it if you can shed some light into this matter, thanks in advance!

**Comment by niujinshuchong** [comment]
@mwang625 Thanks for pointing this out. I think I put a checkpoint of scan37 that's trained for only 200 epochs (you can confirm by `torch.load('scan37.pth')['epoch']`). For all the other scenes, the quantitative results are similar which might be related to some training variants. You can download the meshes trained with 2K epochs here: https://drive.google.com/file/d/1Ty6Nu_sEHbGq6ZYALsM-oQ8Y1O_Pe22v/view?usp=share_link

**Comment by mwang625** [comment]
Thank you so much for checking and uploading the mesh!
