### ISSUE TITLE
 Is there any way we can reduce GPU memory on MonoSDF? 

### ISSUE THREAD

**Issue by ChushanZhang** [autonomousvision/monosdf#61]
Hello there. Thank you for this impressive work!

Since I only get an 8G Vram GPU(RTX 3070), can I run MonoSDF on my GPU?

I checked on the default setting; it seems batch_size is 1, and I cannot reduce it anymore. 

May I have some suggestions from you?

Appreciated.

**Comment by niujinshuchong** [comment]
Hi, you could change the num_pixels to some small value, for example here https://github.com/autonomousvision/monosdf/blob/main/code/confs/dtu_grids_3views.conf#L8. Or you could try to reduce the size of the network.
