### ISSUE TITLE
Evaluation protocol on ScanNet 

### ISSUE THREAD

**Issue by Runsong123** [autonomousvision/monosdf#62]
Dear author,

Thanks for your great work on the scene reconstruction from multi-view images. Currently, I want to follow your evaluation protocol and have some questions about the evaluation code. 

Specifically for ScanNet data, I am wondering if I only need to specify the extracted mesh path (e.g., the path for the provided mesh in this repo) and run "scannet_eval/evaluate.py" file to calculate the metric.

Bests,
Runsong

**Comment by niujinshuchong** [comment]
Yes, you need to update the path here https://github.com/autonomousvision/monosdf/blob/main/scannet_eval/evaluate.py#L140-L146

**Comment by Runsong123** [comment]
Got it. Thanks for your quick reply. :)

Bests,
Runsong
