### ISSUE TITLE
About the rotation of normal map

### ISSUE THREAD

**Issue by KumapowerLIU** [autonomousvision/monosdf#67]
Dear Authors:
Thank you for your great work. After reading the code, I have a question about the normal loss. The normal map between the    omnidata's perdition and the monosdf is different, calculating the loss between these two normal maps should get the rotation, but I do not find the rotation during the loss calculation.

**Comment by niujinshuchong** [comment]
Hi, the code for rotation is here: https://github.com/autonomousvision/monosdf/blob/main/code/model/network.py#L501-L504

**Comment by KumapowerLIU** [comment]
Thank you for your reply.
