### ISSUE TITLE
Replica数据集训练时的报错问题

### ISSUE THREAD

**Issue by ZikangYuan** [autonomousvision/monosdf#68]
作者您好，首先，感谢您开源如此出色的工作。
我在train Replica数据集时遇到了一个问题，由于我本身在该领域是初学者，不太熟悉python代码及pytorch框架，这个问题也查了一天了，但始终查不到确切原因和解决方案，所以只能在issues上向您请教了，希望您能抽时间答疑解惑，感恩不尽。
问题如下：
我直接跑从您提供的sh文件上download下来的Replica数据集，是没有问题的，能正常训练，效果也很好。
但是，您提供的是按照1/20对训练样本降采样之后的Replica数据集，我想测试monosdf在原始训练样本上的效果。
于是，我仿造您提供的nice_slam_apartment的格式转换方式，生成了原始Replica数据集的一下文件：
cameras.npz
每张图片的rgb.png，depth.png，depth.npy，normal.png，nomal.npy，全部都是384x384分辨率
然后在训练时，接收到了如下报错：
![1682748732721](https://user-images.githubusercontent.com/80458592/235287017-914d6bcc-9ca5-4038-a059-660aa2ac6ca1.png)
![1682748759963](https://user-images.githubusercontent.com/80458592/235287040-cd3c50a0-8213-4b22-847e-18e2fe8b81da.png)
如果能得到您的帮助，感恩不尽！

**Comment by niujinshuchong** [comment]
Hi, maybe because we set the maximum value of 1000 here for per-image code https://github.com/autonomousvision/monosdf/blob/main/code/model/network.py#L347-L348 and you are using 2000 images.

**Comment by ZikangYuan** [comment]
Thank you very much！ My problem has been solved by using your solution.
Thanks again!

**Comment by doddodod** [comment]
Hi, did you encounter problems like /root/miniconda3/envs/monosdf/lib/gcc/x86_64-conda-linux-gnu/14.1.0/include/c++/cstdlib:249:22: error: 'div' has not been declared in '__gnu_cxx'
  249 |   using ::__gnu_cxx::div;?

may I ask about your python version, cuda info and gcc info?
