### ISSUE TITLE
Where can I find the chamfer distance for scannet/Replica dataset?

### ISSUE THREAD

**Issue by ChushanZhang** [autonomousvision/monosdf#71]
Dear Authors,

Thanks for this amazing work! 

There is a quick question that I did not directly find Chamfer distance computation in your evaluation py files, could you give me some guidance on this? 

Maybe I miss it somewhere, but for Replica I found"accuracy_rec, completion_rec, precision_ratio_rec, completion_ratio_rec, fscore, normal_acc, normal_comp, normal_avg"; while only "Acc	Comp	Prec	Recall	F-score" for Scannet Evaluation.

Appreciated your help!

**Comment by niujinshuchong** [comment]
@PoopBear1 The chamfer distance is the mean of accuracy_rec and completion_rec.

**Comment by ChushanZhang** [comment]
> 

Much appreciated your reply! I was worried that you did different calculations during the evaluation processing. 😆
