### ISSUE TITLE
Replica Pre-train models are exclusive?

### ISSUE THREAD

**Issue by TobyZack** [autonomousvision/monosdf#72]
Dear Authors,

Appreciated your work,

In the scripts you provided, I was unable to find the Replica meshes, as well as the pre-trained model on the Replica dataset. 

Could you kindly share these with us? 

Thank you!

**Comment by niujinshuchong** [comment]
Hi, replica results can be downloaded here: https://drive.google.com/file/d/1I0gaILNAgy0Exo1tucIeK0UmYRdHGLic/view?usp=share_link

**Comment by TobyZack** [comment]
Thanks for your prompt reply!
