### ISSUE TITLE
Can Monosdf be used in novel view synthesis?

### ISSUE THREAD

**Issue by thucz** [autonomousvision/monosdf#76]
Recently, I submitted an article and the reviewer asked me to compare my method with MonoSDF for the novel view synthesis task. How can I run MonoSDF for the novel view synthesis task with the poses of COLMAP?

**Comment by niujinshuchong** [comment]
Yes, novel view synthesis is supported. I think you first need to convert your colmap data in our format and then train the model. After training, you can render RGB images from any viewpoints. We have some novel view synthesis results on the paper Figure 18.
