### ISSUE TITLE
Question about positional encoding

### ISSUE THREAD

**Issue by Liuyveg** [autonomousvision/monosdf#8]
Hi, I would like to know what encoding functions you have implemented in your work. In term of the color network, is it necessary to map the position `x` and view direction `v` to a higher dimension space with encoding function?

**Comment by niujinshuchong** [comment]
Hi, we used the color network from VolSDF where positional encoding from NeRF is applied to view directions. Please check here: https://github.com/lioryariv/volsdf/blob/main/code/model/network.py#L167-L172

**Comment by Liuyveg** [comment]
Thanks for your kind reply
