### ISSUE TITLE
Train/Test Split in Replica Dataset

### ISSUE THREAD

**Issue by wen-yuan-zhang** [autonomousvision/monosdf#89]
Hello, thanks for your excellent work!
I have a question that how is the replica dataset splitted into train/test dataset? I didn't find the split list in the paper. (May be I missed it..) All the replica scenes are

room0, room1, room2, office0, office1, office2, office3, office4
or in monosdf data, named

scan1, scan2, scan3, scan4, scan5, scan6, scan7, scan8

Could you please provide the train/test split list of the 8 scenes? Thanks a lot!

**Comment by niujinshuchong** [comment]
Hi, the train split is room0, room2, office1, office3, office4.

**Comment by wen-yuan-zhang** [comment]
Thanks a lot for your response!♥
