### ISSUE TITLE
When will the code be open source？

### ISSUE THREAD

**Issue by Thermaloo** [autonomousvision/monosdf#9]
Great work！Could you release your code？

**Comment by niujinshuchong** [comment]
Hi, code is released. Sorry for the late reply.

**Comment by Thermaloo** [comment]
&nbsp;Congratulations！
&nbsp;Neurips 2022！

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "autonomousvision/monosdf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月7日(星期五) 下午4:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [autonomousvision/monosdf] When will the code be open source？ (Issue #9)





 
Hi, code is released. Sorry for the late reply.
